directories:
  output: dist-electron
  buildResources: build
appId: com.traycalculator.app
productName: Tray Calculator
win:
  target: nsis
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
files: []
electronVersion: 29.4.6
